### ISSUE TITLE
Create a Swift Package

### ISSUE THREAD

**Issue by rudrankriyam** [rudrankriyam/SwiftUI-Settings-Screen#2]
- [ ] Create a Swift Package
- [ ] Differentiate the code into reusable forms like a static row or a row with the navigation link.

**Comment by haroutig** [comment]
Any progress on this?

**Comment by rudrankriyam** [comment]
Hi @haroutig, I've to rewrite a lot of parts to make the rows reusable. After I'm done with it, I'll create the Swift Package. Thank you!
